services:
  db:
    image: postgres:15
    container_name: niqatech_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rahimmazouz707
      POSTGRES_DB: niqatechdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  app:
    build: .
    container_name: niqatech_app
    depends_on:
      - db
      - qdrant
    environment:
      DATABASE_URL: postgresql://postgres:Rahimmazouz707@db:5432/niqatechdb
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: sh -c "python3 -m  app.create_db && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
